version: 2
jobs:
  get_data:
      machine:
        # Ubuntu 14.04 with Docker 17.10.0-ce
        image: circleci/classic:201711-01
      environment:
        - TEST_DATA_NAME: "ds114_test2_freesurfer"
        - TEST_DATA_URL: "https://osf.io/yhzzj/?action=download&version=1"
      working_directory: /home/circleci/data
      steps:
        - restore_cache:
            keys:
              - data-v1-
        - save_cache:
           key: data-v1-
           paths:
              - /tmp/data

  build:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /home/circleci/data
    steps:
      - run:
          name: ls
          command: |
            ls /tmp/data

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - get_data
      - build:
          requires:
            - get_data
