version: 2
jobs:
  get_data:
      machine:
        # Ubuntu 14.04 with Docker 17.10.0-ce
        image: circleci/classic:201711-01
      environment:
        - TEST_DATA_NAME: "ds114_test2_freesurfer"
        - TEST_DATA_URL: "https://osf.io/yhzzj/?action=download&version=1"
      working_directory: /home/circleci/data
      steps:
        - restore_cache:
            keys:
              - data-v1-
        - run:
            name: ls1
            command: |
              echo ${TEST_DATA_NAME}
              ls /tmp/data
              if [[ ! -d /tmp/data/${TEST_DATA_NAME} ]]; then
                echo "data not found"
              else
                echo "data found"
              fi
        - persist_to_workspace:
            root: /tmp
            paths:
              - data/*
        - run:
            name: ls2
            command: |
              if [[ ! -d /tmp/data/${TEST_DATA_NAME} ]]; then
                echo "data not found"
              else
                echo "data found"
              fi
        - save_cache:
           key: data-v1-
           paths:
              - /tmp/data

  lsthings:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /home/circleci/data
    steps:
      - run:
          name: ls
          command: |
            ls /tmp/data

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - get_data
      - lsthings:
          requires:
            - get_data
